USER_NOT_FOUND = "User Not Found"
USER_DELETED = "User Deleted"
PASSWORD_CHANGE_SUCCESS = "Password Changed Successfully"
REGISTER_USER_ALREADY_EXISTS = "Register User Already Exists"
REGISTER_INVALID_PASSWORD = "Register Failed Invalid Password"
